### ISSUE TITLE
Tag a stable release

### ISSUE THREAD

**Issue by rcombs** [SAPikachu/flash3kyuu_deband#6]
This is required for inclusion in Homebrew (along with a number of other package managers). There are stable releases in this repo, but the latest one is from 2012.

**Comment by SAPikachu** [comment]
Thanks for the suggestion. The latest commit is stable enough, so I just tagged it as `2.0.0-1` (after minor changes to documentation, `2.0.0` missed that). Please let me know if you find anything missing.
