### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by theChaosCoder** [SAPikachu/flash3kyuu_deband#7]
http://f3kdb.readthedocs.io/en/latest/presets.html

Wouldn't it be better if this:
> y=48/cb=48/cr=48/grainy=48/grainc=48

becomes like this:
> y=48, cb=48, cr=48, grainy=48, grainc=48

so one can copy and paste it more easily.

**Comment by SAPikachu** [comment]
Well, this is not meant to be copied, as we can easily override preset parameters by using both `preset` and separate parameters. Did I miss anything?

**Comment by theChaosCoder** [comment]
Then I'm throwing in: better readability :)

I tried to used f3kdb with lumaDBL(), but couldn't get the presets parameter to work. """medium""" Also didn't work. Hence the copy & paste...

> LumaDBL(dither="f3kdb(range=20,preset="""medium""", keep_tv_range=true ")

**Comment by SAPikachu** [comment]
`preset` is only supported in latest git build (or 2.0 alpha/beta versions), maybe you need to update the plugin?

**Comment by theChaosCoder** [comment]
I'm using 2.0 pre. It's more a LumaDBL issue (or just wrong avisynth syntax) .
A plain f3kdb(range=20, preset="medium", keep_tv_range=true) works of course.

**Comment by SAPikachu** [comment]
Oh OK, I guess it's syntax issue then. try:
```
LumaDBL(dither="""f3kdb(range=20,preset="medium", keep_tv_range=true)""")
```

**Comment by theChaosCoder** [comment]
Omg, of course. Stupid me!! It works now, thx.
